from typing import Literal, NotRequired, TypedDict


FraudSignalType = Literal[
    "amount_anomaly",
    "velocity_anomaly",
    "geo_inconsistency",
    "device_mismatch",
    "merchant_risk",
    "behavioral_deviation",
    "structuring_signal",
    "rapid_chain_movement",
]


class FraudEvidence(TypedDict):
    """Explainable evidence generated by the fraud detection agent."""

    evidence_id: str
    signal_type: FraudSignalType
    description: str
    source: str
    transaction_ids: list[str]
    weight: float
    confidence: float


class FraudHeuristicResult(TypedDict):
    """One deterministic fraud heuristic result."""

    heuristic_id: str
    signal_type: FraudSignalType
    triggered: bool
    score_delta: float
    rationale: str
    evidence_ids: list[str]
    confidence: float


class FraudDetectionResult(TypedDict):
    """Typed response schema for explainable fraud detection."""

    transaction_id: str
    fraud_score: float
    risk_band: Literal["low", "medium", "high", "critical"]
    confidence: float
    signals: list[FraudSignalType]
    evidence: list[FraudEvidence]
    heuristics: list[FraudHeuristicResult]
    geographic_inconsistencies: list[str]
    suspicious_behaviors: list[str]
    escalation_recommendation: Literal[
        "none",
        "analyst_review",
        "senior_review",
        "regulatory_review",
        "temporary_hold",
    ]
    explanation: str
    ai_assisted_summary: NotRequired[str]
    recommended_actions: list[str]
